// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'02568cee985377dee5086c7b00925341a16d813bad353efcbefad3eac99b9bdf'>;
export type ExecutionHash =
  ExecutionHashBase<'6ae92d772d7cd5555d7671d61c7f4d41ea94d9f70222e12f05c71c311571c16e'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly AuthToken: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly tokenHash: CodecTypes['pg/text@1']['output'];
      readonly type: 'EMAIL_VERIFICATION' | 'PASSWORD_RESET';
      readonly centerId: CodecTypes['pg/text@1']['output'];
      readonly expiresAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly usedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly Booking: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly token: CodecTypes['pg/text@1']['output'];
      readonly farmerPhone: CodecTypes['pg/text@1']['output'];
      readonly farmerName: CodecTypes['pg/text@1']['output'] | null;
      readonly bankAccount: CodecTypes['pg/text@1']['output'] | null;
      readonly crop: 'PADDY' | 'WHEAT' | 'MAIZE' | 'OTHER';
      readonly quantity: CodecTypes['pg/int4@1']['output'];
      readonly centerId: CodecTypes['pg/text@1']['output'];
      readonly scheduleId: CodecTypes['pg/text@1']['output'];
      readonly status:
        | 'PENDING'
        | 'SLOT_BOOKED'
        | 'ARRIVED'
        | 'GROSS_WEIGHED'
        | 'QUALITY_CHECKED'
        | 'TARE_WEIGHED'
        | 'ACCEPTED'
        | 'PAYMENT_INITIATED'
        | 'MONEY_TRANSFERRED'
        | 'REJECTED'
        | 'EXPIRED';
      readonly qualityStatus: 'PENDING' | 'PASSED' | 'FAILED';
      readonly paymentStatus: 'NOT_STARTED' | 'INITIATED' | 'CREDITED' | 'FAILED';
      readonly allocatedStart: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly allocatedEnd: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly aadhaarChecked: CodecTypes['pg/bool@1']['output'];
      readonly verifiedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly grossWeightKg: CodecTypes['pg/float8@1']['output'] | null;
      readonly tareWeightKg: CodecTypes['pg/float8@1']['output'] | null;
      readonly netWeightKg: CodecTypes['pg/float8@1']['output'] | null;
      readonly weighedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly moisturePct: CodecTypes['pg/float8@1']['output'] | null;
      readonly foreignMatterPct: CodecTypes['pg/float8@1']['output'] | null;
      readonly qualityCheckedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly basePricePerKg: CodecTypes['pg/float8@1']['output'] | null;
      readonly totalDeductions: CodecTypes['pg/float8@1']['output'] | null;
      readonly finalPayout: CodecTypes['pg/float8@1']['output'] | null;
      readonly paymentRefId: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly ProcurementCenter: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly passwordHash: CodecTypes['pg/text@1']['output'];
      readonly isEmailVerified: CodecTypes['pg/bool@1']['output'];
      readonly pincode: CodecTypes['pg/text@1']['output'];
      readonly location: CodecTypes['pg/text@1']['output'];
      readonly landmark: CodecTypes['pg/text@1']['output'] | null;
      readonly fullAddress: CodecTypes['pg/text@1']['output'] | null;
      readonly acceptedCrops: ReadonlyArray<'PADDY' | 'WHEAT' | 'MAIZE' | 'OTHER'>;
      readonly openTime: CodecTypes['pg/text@1']['output'];
      readonly closeTime: CodecTypes['pg/text@1']['output'];
      readonly timePerFarmer: CodecTypes['pg/int4@1']['output'];
      readonly minBags: CodecTypes['pg/int4@1']['output'];
      readonly currentStorageKg: CodecTypes['pg/int4@1']['output'];
      readonly maxStorageKg: CodecTypes['pg/int4@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly Schedule: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly centerId: CodecTypes['pg/text@1']['output'];
      readonly date: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly totalCapacity: CodecTypes['pg/int4@1']['output'];
      readonly availableCapacity: CodecTypes['pg/int4@1']['output'];
      readonly status: 'AVAILABLE' | 'FULL' | 'CLOSED';
      readonly isSuspended: CodecTypes['pg/bool@1']['output'];
      readonly delayMinutes: CodecTypes['pg/int4@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly AuthToken: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly tokenHash: CodecTypes['pg/text@1']['input'];
      readonly type: 'EMAIL_VERIFICATION' | 'PASSWORD_RESET';
      readonly centerId: CodecTypes['pg/text@1']['input'];
      readonly expiresAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly usedAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly Booking: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly token: CodecTypes['pg/text@1']['input'];
      readonly farmerPhone: CodecTypes['pg/text@1']['input'];
      readonly farmerName: CodecTypes['pg/text@1']['input'] | null;
      readonly bankAccount: CodecTypes['pg/text@1']['input'] | null;
      readonly crop: 'PADDY' | 'WHEAT' | 'MAIZE' | 'OTHER';
      readonly quantity: CodecTypes['pg/int4@1']['input'];
      readonly centerId: CodecTypes['pg/text@1']['input'];
      readonly scheduleId: CodecTypes['pg/text@1']['input'];
      readonly status:
        | 'PENDING'
        | 'SLOT_BOOKED'
        | 'ARRIVED'
        | 'GROSS_WEIGHED'
        | 'QUALITY_CHECKED'
        | 'TARE_WEIGHED'
        | 'ACCEPTED'
        | 'PAYMENT_INITIATED'
        | 'MONEY_TRANSFERRED'
        | 'REJECTED'
        | 'EXPIRED';
      readonly qualityStatus: 'PENDING' | 'PASSED' | 'FAILED';
      readonly paymentStatus: 'NOT_STARTED' | 'INITIATED' | 'CREDITED' | 'FAILED';
      readonly allocatedStart: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly allocatedEnd: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly aadhaarChecked: CodecTypes['pg/bool@1']['input'];
      readonly verifiedAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly grossWeightKg: CodecTypes['pg/float8@1']['input'] | null;
      readonly tareWeightKg: CodecTypes['pg/float8@1']['input'] | null;
      readonly netWeightKg: CodecTypes['pg/float8@1']['input'] | null;
      readonly weighedAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly moisturePct: CodecTypes['pg/float8@1']['input'] | null;
      readonly foreignMatterPct: CodecTypes['pg/float8@1']['input'] | null;
      readonly qualityCheckedAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly basePricePerKg: CodecTypes['pg/float8@1']['input'] | null;
      readonly totalDeductions: CodecTypes['pg/float8@1']['input'] | null;
      readonly finalPayout: CodecTypes['pg/float8@1']['input'] | null;
      readonly paymentRefId: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly ProcurementCenter: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly passwordHash: CodecTypes['pg/text@1']['input'];
      readonly isEmailVerified: CodecTypes['pg/bool@1']['input'];
      readonly pincode: CodecTypes['pg/text@1']['input'];
      readonly location: CodecTypes['pg/text@1']['input'];
      readonly landmark: CodecTypes['pg/text@1']['input'] | null;
      readonly fullAddress: CodecTypes['pg/text@1']['input'] | null;
      readonly acceptedCrops: ReadonlyArray<'PADDY' | 'WHEAT' | 'MAIZE' | 'OTHER'>;
      readonly openTime: CodecTypes['pg/text@1']['input'];
      readonly closeTime: CodecTypes['pg/text@1']['input'];
      readonly timePerFarmer: CodecTypes['pg/int4@1']['input'];
      readonly minBags: CodecTypes['pg/int4@1']['input'];
      readonly currentStorageKg: CodecTypes['pg/int4@1']['input'];
      readonly maxStorageKg: CodecTypes['pg/int4@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly Schedule: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly centerId: CodecTypes['pg/text@1']['input'];
      readonly date: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly totalCapacity: CodecTypes['pg/int4@1']['input'];
      readonly availableCapacity: CodecTypes['pg/int4@1']['input'];
      readonly status: 'AVAILABLE' | 'FULL' | 'CLOSED';
      readonly isSuspended: CodecTypes['pg/bool@1']['input'];
      readonly delayMinutes: CodecTypes['pg/int4@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly authToken: {
      readonly centerId: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly expiresAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly tokenHash: CodecTypes['pg/text@1']['output'];
      readonly type: 'EMAIL_VERIFICATION' | 'PASSWORD_RESET';
      readonly usedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
    };
    readonly booking: {
      readonly aadhaarChecked: CodecTypes['pg/bool@1']['output'];
      readonly allocatedEnd: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly allocatedStart: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly bankAccount: CodecTypes['pg/text@1']['output'] | null;
      readonly basePricePerKg: CodecTypes['pg/float8@1']['output'] | null;
      readonly centerId: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly crop: 'PADDY' | 'WHEAT' | 'MAIZE' | 'OTHER';
      readonly farmerName: CodecTypes['pg/text@1']['output'] | null;
      readonly farmerPhone: CodecTypes['pg/text@1']['output'];
      readonly finalPayout: CodecTypes['pg/float8@1']['output'] | null;
      readonly foreignMatterPct: CodecTypes['pg/float8@1']['output'] | null;
      readonly grossWeightKg: CodecTypes['pg/float8@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly moisturePct: CodecTypes['pg/float8@1']['output'] | null;
      readonly netWeightKg: CodecTypes['pg/float8@1']['output'] | null;
      readonly paymentRefId: CodecTypes['pg/text@1']['output'] | null;
      readonly paymentStatus: 'NOT_STARTED' | 'INITIATED' | 'CREDITED' | 'FAILED';
      readonly qualityCheckedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly qualityStatus: 'PENDING' | 'PASSED' | 'FAILED';
      readonly quantity: CodecTypes['pg/int4@1']['output'];
      readonly scheduleId: CodecTypes['pg/text@1']['output'];
      readonly status:
        | 'PENDING'
        | 'SLOT_BOOKED'
        | 'ARRIVED'
        | 'GROSS_WEIGHED'
        | 'QUALITY_CHECKED'
        | 'TARE_WEIGHED'
        | 'ACCEPTED'
        | 'PAYMENT_INITIATED'
        | 'MONEY_TRANSFERRED'
        | 'REJECTED'
        | 'EXPIRED';
      readonly tareWeightKg: CodecTypes['pg/float8@1']['output'] | null;
      readonly token: CodecTypes['pg/text@1']['output'];
      readonly totalDeductions: CodecTypes['pg/float8@1']['output'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly verifiedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly weighedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
    };
    readonly procurementCenter: {
      readonly acceptedCrops: ReadonlyArray<'PADDY' | 'WHEAT' | 'MAIZE' | 'OTHER'>;
      readonly closeTime: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly currentStorageKg: CodecTypes['pg/int4@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'];
      readonly fullAddress: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly isEmailVerified: CodecTypes['pg/bool@1']['output'];
      readonly landmark: CodecTypes['pg/text@1']['output'] | null;
      readonly location: CodecTypes['pg/text@1']['output'];
      readonly maxStorageKg: CodecTypes['pg/int4@1']['output'];
      readonly minBags: CodecTypes['pg/int4@1']['output'];
      readonly name: CodecTypes['pg/text@1']['output'];
      readonly openTime: CodecTypes['pg/text@1']['output'];
      readonly passwordHash: CodecTypes['pg/text@1']['output'];
      readonly pincode: CodecTypes['pg/text@1']['output'];
      readonly timePerFarmer: CodecTypes['pg/int4@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly schedule: {
      readonly availableCapacity: CodecTypes['pg/int4@1']['output'];
      readonly centerId: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly date: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly delayMinutes: CodecTypes['pg/int4@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly isSuspended: CodecTypes['pg/bool@1']['output'];
      readonly status: 'AVAILABLE' | 'FULL' | 'CLOSED';
      readonly totalCapacity: CodecTypes['pg/int4@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly authToken: {
      readonly centerId: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly expiresAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly tokenHash: CodecTypes['pg/text@1']['input'];
      readonly type: 'EMAIL_VERIFICATION' | 'PASSWORD_RESET';
      readonly usedAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
    };
    readonly booking: {
      readonly aadhaarChecked: CodecTypes['pg/bool@1']['input'];
      readonly allocatedEnd: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly allocatedStart: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly bankAccount: CodecTypes['pg/text@1']['input'] | null;
      readonly basePricePerKg: CodecTypes['pg/float8@1']['input'] | null;
      readonly centerId: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly crop: 'PADDY' | 'WHEAT' | 'MAIZE' | 'OTHER';
      readonly farmerName: CodecTypes['pg/text@1']['input'] | null;
      readonly farmerPhone: CodecTypes['pg/text@1']['input'];
      readonly finalPayout: CodecTypes['pg/float8@1']['input'] | null;
      readonly foreignMatterPct: CodecTypes['pg/float8@1']['input'] | null;
      readonly grossWeightKg: CodecTypes['pg/float8@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly moisturePct: CodecTypes['pg/float8@1']['input'] | null;
      readonly netWeightKg: CodecTypes['pg/float8@1']['input'] | null;
      readonly paymentRefId: CodecTypes['pg/text@1']['input'] | null;
      readonly paymentStatus: 'NOT_STARTED' | 'INITIATED' | 'CREDITED' | 'FAILED';
      readonly qualityCheckedAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly qualityStatus: 'PENDING' | 'PASSED' | 'FAILED';
      readonly quantity: CodecTypes['pg/int4@1']['input'];
      readonly scheduleId: CodecTypes['pg/text@1']['input'];
      readonly status:
        | 'PENDING'
        | 'SLOT_BOOKED'
        | 'ARRIVED'
        | 'GROSS_WEIGHED'
        | 'QUALITY_CHECKED'
        | 'TARE_WEIGHED'
        | 'ACCEPTED'
        | 'PAYMENT_INITIATED'
        | 'MONEY_TRANSFERRED'
        | 'REJECTED'
        | 'EXPIRED';
      readonly tareWeightKg: CodecTypes['pg/float8@1']['input'] | null;
      readonly token: CodecTypes['pg/text@1']['input'];
      readonly totalDeductions: CodecTypes['pg/float8@1']['input'] | null;
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly verifiedAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly weighedAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
    };
    readonly procurementCenter: {
      readonly acceptedCrops: ReadonlyArray<'PADDY' | 'WHEAT' | 'MAIZE' | 'OTHER'>;
      readonly closeTime: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly currentStorageKg: CodecTypes['pg/int4@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'];
      readonly fullAddress: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly isEmailVerified: CodecTypes['pg/bool@1']['input'];
      readonly landmark: CodecTypes['pg/text@1']['input'] | null;
      readonly location: CodecTypes['pg/text@1']['input'];
      readonly maxStorageKg: CodecTypes['pg/int4@1']['input'];
      readonly minBags: CodecTypes['pg/int4@1']['input'];
      readonly name: CodecTypes['pg/text@1']['input'];
      readonly openTime: CodecTypes['pg/text@1']['input'];
      readonly passwordHash: CodecTypes['pg/text@1']['input'];
      readonly pincode: CodecTypes['pg/text@1']['input'];
      readonly timePerFarmer: CodecTypes['pg/int4@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly schedule: {
      readonly availableCapacity: CodecTypes['pg/int4@1']['input'];
      readonly centerId: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly date: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly delayMinutes: CodecTypes['pg/int4@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly isSuspended: CodecTypes['pg/bool@1']['input'];
      readonly status: 'AVAILABLE' | 'FULL' | 'CLOSED';
      readonly totalCapacity: CodecTypes['pg/int4@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly authToken: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly tokenHash: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly type: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly centerId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly expiresAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly usedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['tokenHash'] }];
              indexes: readonly [
                {
                  readonly name: 'authToken_centerId_idx_57ced294';
                  readonly prefix: 'authToken_centerId_idx';
                  readonly columns: readonly ['centerId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'authToken';
                    readonly columns: readonly ['centerId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'procurementCenter';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly booking: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly token: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly farmerPhone: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly farmerName: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly bankAccount: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly crop: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly quantity: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly centerId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly scheduleId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'PENDING'>;
                  };
                };
                readonly qualityStatus: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'PENDING'>;
                  };
                };
                readonly paymentStatus: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'NOT_STARTED'>;
                  };
                };
                readonly allocatedStart: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                };
                readonly allocatedEnd: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                };
                readonly aadhaarChecked: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly verifiedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                };
                readonly grossWeightKg: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: true;
                };
                readonly tareWeightKg: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: true;
                };
                readonly netWeightKg: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: true;
                };
                readonly weighedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                };
                readonly moisturePct: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: true;
                };
                readonly foreignMatterPct: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: true;
                };
                readonly qualityCheckedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                };
                readonly basePricePerKg: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: true;
                };
                readonly totalDeductions: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: true;
                };
                readonly finalPayout: {
                  readonly nativeType: 'float8';
                  readonly codecId: 'pg/float8@1';
                  readonly nullable: true;
                };
                readonly paymentRefId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['token'] }];
              indexes: readonly [
                {
                  readonly name: 'booking_centerId_idx_57ced294';
                  readonly prefix: 'booking_centerId_idx';
                  readonly columns: readonly ['centerId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'booking_scheduleId_idx_5a3bfbcb';
                  readonly prefix: 'booking_scheduleId_idx';
                  readonly columns: readonly ['scheduleId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'booking';
                    readonly columns: readonly ['centerId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'procurementCenter';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'booking';
                    readonly columns: readonly ['scheduleId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'schedule';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly procurementCenter: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly passwordHash: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly isEmailVerified: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly pincode: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly location: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly landmark: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly fullAddress: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly acceptedCrops: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly openTime: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly closeTime: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly timePerFarmer: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly minBags: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 1>;
                  };
                };
                readonly currentStorageKg: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly maxStorageKg: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['email'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly schedule: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly centerId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly date: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
                readonly totalCapacity: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly availableCapacity: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'AVAILABLE'>;
                  };
                };
                readonly isSuspended: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly delayMinutes: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['centerId', 'date'] }];
              indexes: readonly [
                {
                  readonly name: 'schedule_centerId_idx_57ced294';
                  readonly prefix: 'schedule_centerId_idx';
                  readonly columns: readonly ['centerId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'schedule';
                    readonly columns: readonly ['centerId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'procurementCenter';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
          };
          readonly valueSet: {
            readonly BookingStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly [
                'PENDING',
                'SLOT_BOOKED',
                'ARRIVED',
                'GROSS_WEIGHED',
                'QUALITY_CHECKED',
                'TARE_WEIGHED',
                'ACCEPTED',
                'PAYMENT_INITIATED',
                'MONEY_TRANSFERRED',
                'REJECTED',
                'EXPIRED',
              ];
            };
            readonly CropType: {
              readonly kind: 'valueSet';
              readonly values: readonly ['PADDY', 'WHEAT', 'MAIZE', 'OTHER'];
            };
            readonly PaymentStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['NOT_STARTED', 'INITIATED', 'CREDITED', 'FAILED'];
            };
            readonly QualityStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['PENDING', 'PASSED', 'FAILED'];
            };
            readonly SlotStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['AVAILABLE', 'FULL', 'CLOSED'];
            };
            readonly TokenType: {
              readonly kind: 'valueSet';
              readonly values: readonly ['EMAIL_VERIFICATION', 'PASSWORD_RESET'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly procurementCenter: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'ProcurementCenter';
    };
    readonly authToken: { readonly namespace: 'public' & NamespaceId; readonly model: 'AuthToken' };
    readonly schedule: { readonly namespace: 'public' & NamespaceId; readonly model: 'Schedule' };
    readonly booking: { readonly namespace: 'public' & NamespaceId; readonly model: 'Booking' };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly AuthToken: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly tokenHash: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly type: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly centerId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly expiresAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly usedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly center: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ProcurementCenter';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['centerId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'authToken';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly tokenHash: { readonly column: 'tokenHash' };
                readonly type: { readonly column: 'type' };
                readonly centerId: { readonly column: 'centerId' };
                readonly expiresAt: { readonly column: 'expiresAt' };
                readonly usedAt: { readonly column: 'usedAt' };
                readonly createdAt: { readonly column: 'createdAt' };
              };
            };
          };
          readonly Booking: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly token: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly farmerPhone: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly farmerName: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly bankAccount: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly crop: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly quantity: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly centerId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly scheduleId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly qualityStatus: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly paymentStatus: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly allocatedStart: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly allocatedEnd: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly aadhaarChecked: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly verifiedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly grossWeightKg: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly tareWeightKg: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly netWeightKg: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly weighedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly moisturePct: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly foreignMatterPct: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly qualityCheckedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly basePricePerKg: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly totalDeductions: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly finalPayout: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/float8@1' };
              };
              readonly paymentRefId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly center: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ProcurementCenter';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['centerId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly schedule: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Schedule';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['scheduleId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'booking';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly token: { readonly column: 'token' };
                readonly farmerPhone: { readonly column: 'farmerPhone' };
                readonly farmerName: { readonly column: 'farmerName' };
                readonly bankAccount: { readonly column: 'bankAccount' };
                readonly crop: { readonly column: 'crop' };
                readonly quantity: { readonly column: 'quantity' };
                readonly centerId: { readonly column: 'centerId' };
                readonly scheduleId: { readonly column: 'scheduleId' };
                readonly status: { readonly column: 'status' };
                readonly qualityStatus: { readonly column: 'qualityStatus' };
                readonly paymentStatus: { readonly column: 'paymentStatus' };
                readonly allocatedStart: { readonly column: 'allocatedStart' };
                readonly allocatedEnd: { readonly column: 'allocatedEnd' };
                readonly aadhaarChecked: { readonly column: 'aadhaarChecked' };
                readonly verifiedAt: { readonly column: 'verifiedAt' };
                readonly grossWeightKg: { readonly column: 'grossWeightKg' };
                readonly tareWeightKg: { readonly column: 'tareWeightKg' };
                readonly netWeightKg: { readonly column: 'netWeightKg' };
                readonly weighedAt: { readonly column: 'weighedAt' };
                readonly moisturePct: { readonly column: 'moisturePct' };
                readonly foreignMatterPct: { readonly column: 'foreignMatterPct' };
                readonly qualityCheckedAt: { readonly column: 'qualityCheckedAt' };
                readonly basePricePerKg: { readonly column: 'basePricePerKg' };
                readonly totalDeductions: { readonly column: 'totalDeductions' };
                readonly finalPayout: { readonly column: 'finalPayout' };
                readonly paymentRefId: { readonly column: 'paymentRefId' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly ProcurementCenter: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly passwordHash: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly isEmailVerified: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly pincode: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly location: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly landmark: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly fullAddress: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly acceptedCrops: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
                readonly many: true;
              };
              readonly openTime: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly closeTime: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly timePerFarmer: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly minBags: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly currentStorageKg: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly maxStorageKg: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly authTokens: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'AuthToken';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['centerId'];
                };
              };
              readonly bookings: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Booking';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['centerId'];
                };
              };
              readonly schedules: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Schedule';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['centerId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'procurementCenter';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly name: { readonly column: 'name' };
                readonly email: { readonly column: 'email' };
                readonly passwordHash: { readonly column: 'passwordHash' };
                readonly isEmailVerified: { readonly column: 'isEmailVerified' };
                readonly pincode: { readonly column: 'pincode' };
                readonly location: { readonly column: 'location' };
                readonly landmark: { readonly column: 'landmark' };
                readonly fullAddress: { readonly column: 'fullAddress' };
                readonly acceptedCrops: { readonly column: 'acceptedCrops' };
                readonly openTime: { readonly column: 'openTime' };
                readonly closeTime: { readonly column: 'closeTime' };
                readonly timePerFarmer: { readonly column: 'timePerFarmer' };
                readonly minBags: { readonly column: 'minBags' };
                readonly currentStorageKg: { readonly column: 'currentStorageKg' };
                readonly maxStorageKg: { readonly column: 'maxStorageKg' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly Schedule: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly centerId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly date: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly totalCapacity: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly availableCapacity: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly isSuspended: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly delayMinutes: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly bookings: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Booking';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['scheduleId'];
                };
              };
              readonly center: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ProcurementCenter';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['centerId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'schedule';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly centerId: { readonly column: 'centerId' };
                readonly date: { readonly column: 'date' };
                readonly totalCapacity: { readonly column: 'totalCapacity' };
                readonly availableCapacity: { readonly column: 'availableCapacity' };
                readonly status: { readonly column: 'status' };
                readonly isSuspended: { readonly column: 'isSuspended' };
                readonly delayMinutes: { readonly column: 'delayMinutes' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
        };
        readonly enum: {
          readonly BookingStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'PENDING'; readonly value: 'PENDING' },
              { readonly name: 'SLOT_BOOKED'; readonly value: 'SLOT_BOOKED' },
              { readonly name: 'ARRIVED'; readonly value: 'ARRIVED' },
              { readonly name: 'GROSS_WEIGHED'; readonly value: 'GROSS_WEIGHED' },
              { readonly name: 'QUALITY_CHECKED'; readonly value: 'QUALITY_CHECKED' },
              { readonly name: 'TARE_WEIGHED'; readonly value: 'TARE_WEIGHED' },
              { readonly name: 'ACCEPTED'; readonly value: 'ACCEPTED' },
              { readonly name: 'PAYMENT_INITIATED'; readonly value: 'PAYMENT_INITIATED' },
              { readonly name: 'MONEY_TRANSFERRED'; readonly value: 'MONEY_TRANSFERRED' },
              { readonly name: 'REJECTED'; readonly value: 'REJECTED' },
              { readonly name: 'EXPIRED'; readonly value: 'EXPIRED' },
            ];
          };
          readonly CropType: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'PADDY'; readonly value: 'PADDY' },
              { readonly name: 'WHEAT'; readonly value: 'WHEAT' },
              { readonly name: 'MAIZE'; readonly value: 'MAIZE' },
              { readonly name: 'OTHER'; readonly value: 'OTHER' },
            ];
          };
          readonly QualityStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'PENDING'; readonly value: 'PENDING' },
              { readonly name: 'PASSED'; readonly value: 'PASSED' },
              { readonly name: 'FAILED'; readonly value: 'FAILED' },
            ];
          };
          readonly PaymentStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'NOT_STARTED'; readonly value: 'NOT_STARTED' },
              { readonly name: 'INITIATED'; readonly value: 'INITIATED' },
              { readonly name: 'CREDITED'; readonly value: 'CREDITED' },
              { readonly name: 'FAILED'; readonly value: 'FAILED' },
            ];
          };
          readonly SlotStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'AVAILABLE'; readonly value: 'AVAILABLE' },
              { readonly name: 'FULL'; readonly value: 'FULL' },
              { readonly name: 'CLOSED'; readonly value: 'CLOSED' },
            ];
          };
          readonly TokenType: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'EMAIL_VERIFICATION'; readonly value: 'EMAIL_VERIFICATION' },
              { readonly name: 'PASSWORD_RESET'; readonly value: 'PASSWORD_RESET' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'authToken';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'booking';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'booking';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'procurementCenter';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'procurementCenter';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'schedule';
            readonly column: 'id';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'uuidv4' };
        },
        {
          readonly ref: {
            readonly namespace: 'public';
            readonly table: 'schedule';
            readonly column: 'updatedAt';
          };
          readonly onCreate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
          readonly onUpdate: { readonly kind: 'generator'; readonly id: 'timestampNow' };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
